package com.ozner.cup.DBHelper;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ozner.cup.DBHelper.EMMessage;
import com.ozner.cup.DBHelper.UserInfo;
import com.ozner.cup.DBHelper.WaterPurifierAttr;
import com.ozner.cup.DBHelper.FriendRankItem;

import com.ozner.cup.DBHelper.EMMessageDao;
import com.ozner.cup.DBHelper.UserInfoDao;
import com.ozner.cup.DBHelper.WaterPurifierAttrDao;
import com.ozner.cup.DBHelper.FriendRankItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eMMessageDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig waterPurifierAttrDaoConfig;
    private final DaoConfig friendRankItemDaoConfig;

    private final EMMessageDao eMMessageDao;
    private final UserInfoDao userInfoDao;
    private final WaterPurifierAttrDao waterPurifierAttrDao;
    private final FriendRankItemDao friendRankItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eMMessageDaoConfig = daoConfigMap.get(EMMessageDao.class).clone();
        eMMessageDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        waterPurifierAttrDaoConfig = daoConfigMap.get(WaterPurifierAttrDao.class).clone();
        waterPurifierAttrDaoConfig.initIdentityScope(type);

        friendRankItemDaoConfig = daoConfigMap.get(FriendRankItemDao.class).clone();
        friendRankItemDaoConfig.initIdentityScope(type);

        eMMessageDao = new EMMessageDao(eMMessageDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        waterPurifierAttrDao = new WaterPurifierAttrDao(waterPurifierAttrDaoConfig, this);
        friendRankItemDao = new FriendRankItemDao(friendRankItemDaoConfig, this);

        registerDao(EMMessage.class, eMMessageDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(WaterPurifierAttr.class, waterPurifierAttrDao);
        registerDao(FriendRankItem.class, friendRankItemDao);
    }
    
    public void clear() {
        eMMessageDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        waterPurifierAttrDaoConfig.clearIdentityScope();
        friendRankItemDaoConfig.clearIdentityScope();
    }

    public EMMessageDao getEMMessageDao() {
        return eMMessageDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public WaterPurifierAttrDao getWaterPurifierAttrDao() {
        return waterPurifierAttrDao;
    }

    public FriendRankItemDao getFriendRankItemDao() {
        return friendRankItemDao;
    }

}
