package com.ozner.cup.DBHelper;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ozner.cup.DBHelper.WaterPurifierAttr;

import com.ozner.cup.DBHelper.WaterPurifierAttrDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig waterPurifierAttrDaoConfig;

    private final WaterPurifierAttrDao waterPurifierAttrDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        waterPurifierAttrDaoConfig = daoConfigMap.get(WaterPurifierAttrDao.class).clone();
        waterPurifierAttrDaoConfig.initIdentityScope(type);

        waterPurifierAttrDao = new WaterPurifierAttrDao(waterPurifierAttrDaoConfig, this);

        registerDao(WaterPurifierAttr.class, waterPurifierAttrDao);
    }
    
    public void clear() {
        waterPurifierAttrDaoConfig.clearIdentityScope();
    }

    public WaterPurifierAttrDao getWaterPurifierAttrDao() {
        return waterPurifierAttrDao;
    }

}
